name: camera_face_analysis
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9

  image: ^4.0.17
  path_provider: ^2.1.5
  path: ^1.9.1
  google_mlkit_face_detection: ^0.13.1
  tflite_flutter: ^0.11.0
  google_mlkit_image_labeling: ^0.14.1
  google_mlkit_object_detection: ^0.15.0
  google_mlkit_commons: ^0.11.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
